default_platform(:ios)

platform :ios do
  lane :beta do
    increment_build_number(
      xcodeproj: "Locus.xcodeproj"
    )
    build_app(
      workspace: "Locus.xcworkspace",
      scheme: "Locus",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
